import { describe, expect, it } from 'vitest'
import pkg from './chat-session-lock.cjs'

const { createChatSessionLock } = pkg as {
    createChatSessionLock: (opts?: { now?: () => number, ttlMs?: number }) => {
        claim: (key: string, clientId: string, sessionId?: string) => { ok: boolean, reason?: string }
        checkWrite: (key: string, clientId: string) => { ok: boolean, reason?: string, leased?: boolean }
        release: (key: string, clientId: string) => { released: boolean }
        activeCount: () => number
    }
}

describe('chat-session-lock', () => {
    it('allows different chats to be generated by different devices', () => {
        const lock = createChatSessionLock()
        expect(lock.claim('char-a/chat-a', 'pc').ok).toBe(true)
        expect(lock.claim('char-b/chat-b', 'phone').ok).toBe(true)
        expect(lock.checkWrite('char-a/chat-a', 'pc')).toMatchObject({ ok: true, leased: true })
        expect(lock.checkWrite('char-b/chat-b', 'phone')).toMatchObject({ ok: true, leased: true })
    })

    it('rejects another page only for the same chat', () => {
        const lock = createChatSessionLock()
        expect(lock.claim('char-a/chat-a', 'pc').ok).toBe(true)
        expect(lock.claim('char-a/chat-a', 'phone')).toMatchObject({ ok: false, reason: 'busy' })
        expect(lock.checkWrite('char-a/chat-a', 'phone')).toEqual({ ok: false, reason: 'busy' })
    })

    it('renews for the owner and releases only for the owner', () => {
        const lock = createChatSessionLock()
        expect(lock.claim('char-a/chat-a', 'pc').ok).toBe(true)
        expect(lock.claim('char-a/chat-a', 'pc').ok).toBe(true)
        expect(lock.release('char-a/chat-a', 'phone').released).toBe(false)
        expect(lock.release('char-a/chat-a', 'pc').released).toBe(true)
        expect(lock.claim('char-a/chat-a', 'phone').ok).toBe(true)
    })

    it('expires an abandoned page lease', () => {
        let time = 1_000
        const lock = createChatSessionLock({ now: () => time, ttlMs: 2_000 })
        expect(lock.claim('char-a/chat-a', 'dead-page').ok).toBe(true)
        time += 2_001
        expect(lock.claim('char-a/chat-a', 'new-page').ok).toBe(true)
        expect(lock.activeCount()).toBe(1)
    })
})
