name: pocketrisu

services:
  risuai:
    container_name: pocketrisu
    image: ghcr.io/pocketrisu/pocketrisu:latest
    restart: always
    ports:
      - 6001:6001
    volumes:
      - risuai-save:/app/save

volumes:
  risuai-save:
